version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "tripper"
      POSTGRES_USER: "mayank_ughade"
      POSTGRES_PASSWORD: "mayank@14"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
